purbeurre/main/urls.py
from django.urls import path
from . import views
from django.views.generic import RedirectView


app_name = "main"  # here for namespacing of urls.

urlpatterns = [
    path("", views.HomepageView.as_view(), name="homepage"),
    path("register/", views.register, name="register"),
    path("logout/", views.logout_request, name="logout"),
    path("login/", views.login_request, name="login"),
    path("aliments/", views.aliments, name="aliments"),
    path("account/", views.account, name="account"),
    path("mentions/", views.mentions, name="mentions"),
    path(
        "delete-from-main/<int:aliment_id>/",
        views.delete_from_main,
        name="delete_from_main",
    ),
    path("infos/<int:aliment_id>/", views.infos, name="infos"),
    path("save_aliment/<int:aliment_id>/", views.save_aliment, name="save_aliment",),
    path("saved/", views.saved, name="saved"),
    path("delete/<int:aliment_id>/", views.delete, name="delete"),
    path("alternative/<int:aliment_id>", views.alternative, name="alternative"),
    path("send_infos/", views.send_infos, name="send_infos"),
]

purbeurre/purbeurre/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

purbeurre/main/models.py
from django.db import models
from django.contrib.auth.models import User


class Aliment(models.Model):
    """
    This class represents all the informations
    fetched from the REST API of the
    OpenFoodFact project
    """

    name = models.CharField(max_length=200)
    name_fr = models.CharField(max_length=200)
    date = models.TextField(max_length=100)
    brands = models.CharField(max_length=200)
    nutriscore = models.CharField(max_length=100)
    ingredients = models.TextField()
    image = models.URLField(max_length=255)
    url = models.URLField(max_length=255)
    stores = models.CharField(max_length=300)
    quantity = models.CharField(max_length=300)
    packaging = models.CharField(max_length=600)
    ingredients_fr = models.TextField()
    manufactured_places = models.CharField(max_length=1000)
    purchase_places = models.CharField(max_length=500)
    categories = models.TextField()
    code = models.CharField(max_length=200)

    def __repr__(self):
        return self.name

    def __str__(self):
        return self.name


class Favorite(models.Model):
    """
    This class is used to associate the aliments saved
    by a specific User
    """

    saved_by = models.ForeignKey(User, on_delete=models.CASCADE)
    saved_aliment = models.ForeignKey(Aliment, on_delete=models.CASCADE)

    def __str__(self):

        return f"{self.saved_by} -- {self.saved_aliment}"

purbeurre/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserFormWithEmail(UserCreationForm):
    email = forms.EmailField(required=True)

    def __init__(self, *args, **kwargs):
        super(UserFormWithEmail, self).__init__(*args, **kwargs)

        for fieldname in ["username", "email", "password1", "password2"]:
            self.fields[fieldname].help_text = None

    def save(self, commit=True):
        user = super(UserFormWithEmail, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

purbeurre/main/views.py
from django.http import HttpResponse, HttpResponseRedirect, HttpRequest
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import logout, authenticate, login
from django.shortcuts import render, redirect
from django.db.models import Q
from django.contrib import messages
from .forms import UserFormWithEmail
from .models import Aliment, Favorite
from .form_aliment import FormAliment
from django.contrib import messages
from django.core.mail import EmailMultiAlternatives
from django.conf import settings
from django.template.loader import render_to_string, get_template
import time
from django.views.decorators.csrf import requires_csrf_token
from django.http import JsonResponse
import json
from django.core.mail import EmailMultiAlternatives
from django.conf import settings
from django.template.loader import render_to_string, get_template
from django.http import JsonResponse
from django.views.generic import TemplateView

# Corrected the 23-04-2020
class HomepageView(TemplateView):
    template_name = "main/homepage.html"


def register(request):
    """
    This function returns the register form template
    """
    if request.method == "POST":
        form = UserFormWithEmail(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f"Bienvenue {username}, votre profile est créé!")
            login(request, user)

            return redirect("main:homepage")
        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg}: {form.error_messages[msg]}")

            return render(
                request=request,
                template_name="main/register.html",
                context={"form": form},
            )

    form = UserFormWithEmail
    return render(
        request=request, template_name="main/register.html", context={"form": form},
    )


def logout_request(request):
    """
    This function is used by the user to logout
    """
    if request.user.is_authenticated:
        logout(request)
        messages.success(request, f"Déconnecté")
        return redirect("main:homepage")
    else:
        return redirect("main:homepage")


def login_request(request):
    """
    This functions is used to get the user logged if
    the Auth is auth is success
    """
    if request.user.is_authenticated:
        return redirect("/")
    else:

        if request.method == "POST":
            form = AuthenticationForm(request=request, data=request.POST)
            if form.is_valid():
                username = form.cleaned_data.get("username")
                password = form.cleaned_data.get("password")
                user = authenticate(username=username, password=password)
                if user is not None:
                    login(request, user)
                    messages.success(request, f"Bienvenue {user.username}")
                    return redirect("/")
                else:
                    pass
            else:
                pass
        form = AuthenticationForm()
        return render(
            request=request, template_name="main/login.html", context={"form": form},
        )


def aliments(request):
    """
    This function returns the results of the initial search
    """
    user = request.user
    aliments_saved = Favorite.objects.filter(saved_by=user.id)
    count = len(aliments_saved)
    flist = []
    for i in aliments_saved:
        flist.append(i.saved_aliment.id)

    fav_aliments = Aliment.objects.filter(pk__in=flist)
    aliments = Favorite.objects.filter(saved_by=user.id)
    count = len(aliments)
    flist = []
    for i in aliments:
        flist.append(i.saved_aliment.id)

    favorites = Aliment.objects.filter(pk__in=flist)
    count_saved = len(favorites)
    aliment_list = Aliment.objects.all()
    query = request.GET.get("aliments")
    if query:
        query = query.capitalize()
        aliment_list = (
            Aliment.objects.filter(name__startswith=query,)
            .exclude(nutriscore="non disponible",)
            .exclude(brands="non disponible")
        )

        aliment_count = aliment_list.count()

        complete_list = zip(fav_aliments, aliment_list)

        paginator = Paginator(aliment_list, 6)  # 6 posts per page
        page = request.GET.get("page")

        try:
            aliments = paginator.page(page)
        except PageNotAnInteger:
            aliments = paginator.page(1)
        except EmptyPage:
            aliments = paginator.page(paginator.num_pages)
        context = {
            "fav_aliments": fav_aliments,
            "aliments": aliments,
            "count": aliment_count,
            "query": query,
            "counted_saved": count_saved,
        }
        return render(request, "main/aliments.html", context)
    else:
        return redirect("/")


def account(request):
    """
    This function return the account html templates with the users
    informations
    """
    user = request.user
    aliments = Favorite.objects.filter(saved_by=user.id)

    flist = []
    for i in aliments:
        flist.append(i.saved_aliment.id)

    aliments_list = Aliment.objects.filter(pk__in=flist)
    total = aliments_list.count()
    context = {"total": total}
    if request.user.is_authenticated:
        return render(request, "main/account.html", context)
    else:
        return redirect("/")


def infos(request, aliment_id):
    """
    This function returns an html template with infos about the
    selected aliment
    """
    aliment = Aliment.objects.get(id=aliment_id)
    date = aliment.date
    date = date[2:12]
    context = {"aliment": aliment, "date": date, "aliment_id": aliment_id}

    return render(request, "main/infos.html", context)


def save_aliment(request, aliment_id):
    """
    This view adds the selected aliment to the database
    """
    path = request.META.get("HTTP_REFERER")
    aliment = Aliment.objects.get(id=aliment_id)
    saved_aliment = Favorite(saved_by=request.user, saved_aliment=aliment)
    saved_aliment.save()
    saved = Favorite.objects.count()
    query = aliment.name
    query = query.split(" ")
    query = query[0]

    if query:
        aliment_list = (
            Aliment.objects.filter(name__startswith=query,)
            .exclude(nutriscore="non disponible",)
            .exclude(brands="non disponible")
        )
        aliment_count = aliment_list.count()

    paginator = Paginator(aliment_list, 6)  # 6 posts per page
    page = request.GET.get("page")

    try:
        aliments = paginator.page(page)
    except PageNotAnInteger:
        aliments = paginator.page(1)
    except EmptyPage:
        aliments = paginator.page(paginator.num_pages)
    messages.success(request, f"Aliment sauvegardé!")

    return redirect(path)


def alternative(request, aliment_id):
    """
    This view renders an html template with alternative products
    """
    path = request.META.get("HTTP_REFERER")

    try:
        aliment = Aliment.objects.get(id=aliment_id)
    except Aliment.DoesNotExist:
        return redirect("/homepage/")

    categorie = aliment.categories
    categorie_list = categorie.split(" ")
    cat_for_query = categorie_list[0]
    aliment_list = Aliment.objects.filter(
        categories__startswith=cat_for_query, nutriscore="a"
    )
    total = len(aliment_list)

    if total == 0:
        aliment_list = Aliment.objects.filter(
            categories__startswith=cat_for_query, nutriscore="b"
        )
        total = len(aliment_list)
        if total == 0:
            aliment_list = Aliment.objects.filter(
                categories__startswith=cat_for_query, nutriscore="c"
            )
            total = len(aliment_list)
        if total == 0:
            aliment_list = Aliment.objects.filter(
                categories__startswith=cat_for_query, nutriscore="d"
            )
            total = len(aliment_list)

    paginator = Paginator(aliment_list, 6)  # 6 posts per page
    page = request.GET.get("page")

    try:
        aliments = paginator.page(page)
    except PageNotAnInteger:
        aliments = paginator.page(1)
    except EmptyPage:
        aliments = paginator.page(paginator.num_pages)

    context = {"aliments": aliments, "total": total}

    return render(request, "main/alternative.html", context)


def delete(request, aliment_id):
    """This view is used to delete a saved aliment"""

    if request.user.is_authenticated:
        user = request.user
        aliment = Aliment.objects.filter(id=aliment_id)
        favorite_aliment = Favorite.objects.filter(
            saved_aliment__in=aliment, saved_by=user.id
        )
        favorite_aliment.delete()
        return redirect("/saved")
    else:
        return redirect("/saved")


def saved(request):
    """This view is used to a save an aliment"""

    user = request.user
    aliments = Favorite.objects.filter(saved_by=user.id)
    count = len(aliments)
    flist = []
    for i in aliments:
        flist.append(i.saved_aliment.id)

    aliments_list = Aliment.objects.filter(pk__in=flist)
    paginator = Paginator(aliments_list, 6)  # Show 25 contacts per page

    page = request.GET.get("page")
    aliments = paginator.get_page(page)

    context = {
        "aliments": aliments,
        "count": count,
    }
    if user.is_authenticated:
        return render(request, "main/saved.html", context)
    else:
        return redirect("main:login")


def mentions(request):
    """This view is used to display the mentions page"""

    return render(request, "main/mentions.html")


def delete_from_main(request, aliment_id):
    """
    This view is used to delete a saved aliment
    from the main aliment page
    """
    path = request.META.get("HTTP_REFERER")

    if request.user.is_authenticated:
        user = request.user

purbeurre/main/templates/main/aliments.html
{% extends 'main/homepage.html' %} {% block content %} {% load bootstrap4 %}

<!-- About Section -->
<section class="page-section bg-primary" id="about" style="height: 16em;">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 text-center">
                <h3 class="text-white mt-0">Nous avons trouvé {{count}} aliment(s) correspondant(s) à votre recherche</h3>
            </div>
        </div>
    </div>
</section>
<section>
    <header class="masthead" style="padding-top:10px">
        <div class="row justify-content-center align-items-center " style="margin-top: 1%;">
            {% if count != 0 %} {% for aliment in aliments %}
            <div class="card m-3 flex align-items-stretch" style="width: 23rem; height: 19rem;">
                {% if aliment.nutriscore == 'a' %}
                <div class='nutri' style="width: 40px;border-style: solid; border-color: aliceblue; height: 40px;text-align: center; color:white;background-color: green; border-radius: 50%; margin-left: 95%;margin-top: -5%; position:absolute; padding-top: 6px;">
                    {{aliment.nutriscore|upper}}</div>
                {% elif aliment.nutriscore == 'b' %}
                <div class='nutri' style="width: 40px;border-style: solid; border-color: aliceblue; height: 40px;text-align: center; color:white;background-color: #32CD32; border-radius: 50%; margin-left: 95%;margin-top: -5%; position:absolute; padding-top: 6px;">
                    {{aliment.nutriscore|upper}}</div>
                {% elif aliment.nutriscore == 'c' %}
                <div class='nutri' style="width: 40px;border-style: solid; border-color: aliceblue; height: 40px;text-align: center; color:white;background-color: #FFD700; border-radius: 50%; margin-left: 95%;margin-top: -5%; position:absolute; padding-top: 6px;">
                    {{aliment.nutriscore|upper}}</div>
                {% elif aliment.nutriscore == 'd' %}
                <div class='nutri' style="width: 40px;border-style: solid; border-color: aliceblue; height: 40px;text-align: center; color:white;background-color: #FFA500; border-radius: 50%; margin-left: 95%;margin-top: -5%; position:absolute; padding-top: 6px;">
                    {{aliment.nutriscore|upper}}</div>
                {% elif aliment.nutriscore == 'e' %}
                <div class='nutri' style="width: 40px;border-style: solid; border-color: aliceblue; height: 40px;text-align: center; color:white;background-color:  #FF0000; border-radius: 50%; margin-left: 95%;margin-top: -5%; position:absolute; padding-top: 6px;">
                    {{aliment.nutriscore|upper}}</div>
                {% endif %}
                <div class="card-body" style="text-align: center;">

                    <img class="card-img-top mx-auto d-block" src="{{aliment.image}}" alt="Card image cap" style="width: 160px; height: 160px;">
                    <h5 class="card-title" style="margin-top: 20px;">{{aliment.name|slice:":27" }}...</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Marque: {{aliment.brands|slice:":30"}}</h6>
                    <div class="container">
                        <a href="{% url 'main:infos' aliment_id=aliment.id %}" id="getinfos" class="card-link"><i class="fa fa-info-circle"
                style="font-size:18px"></i>
              Infos</a> {% if user.is_authenticated %} {% if aliment in fav_aliments %}
                        <a href="{% url 'main:alternative' aliment_id=aliment.id %}" class="card-link" title="Alternative" style="margin-left: 80px;"><i class="fas fa-exchange-alt fa-2x"></i></a>

                        <a href="{% url 'main:delete_from_main' aliment_id=aliment.id %}" class="card-link" style="padding-left: 0px;"><i class="fa fa-trash " style="font-size:26px;"></i>
            </a> {% else %}
                        <a href="{% url 'main:alternative' aliment_id=aliment.id %}" class="card-link" title="Alternative" style="margin-left: 80px;"><i class="fas fa-exchange-alt fa-2x"></i></a>
                        <a href="{% url 'main:save_aliment' aliment_id=aliment.id %}" class="card-link" title="Enregistrer"><i
                class="fas fa-save fa-2x"></i></a> {% endif %} {% else %} {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %} {% endif %}
        </div>

        <div class="pagination justify-content-center align-items-center">
            {% if aliments.has_other_pages %}
            <ul class="pagination">
                {% if aliments.has_previous %}
                <li class="waves-effect"><a href="?page=
                    {{ aliments.previous_page_number }}{% if request.GET.aliments %}&aliments={{ request.GET.aliments }}{% endif %}"><i
              class="material-icons" style="margin-right: 10px;"> précédents </i></a></li>
                {% else %}
                <li class="disabled"><a href="#!"><i class="material-icons" style="margin-right: 10px;"> précédents</i></a></li>
                {% endif %} {% if aliments.has_next %}
                <li class="waves-effect"><a href="?page={{ aliments.next_page_number }}{% if request.GET.aliments %}&aliments={{ request.GET.aliments }}{% endif %}"><i
              class="material-icons" style="margin-left: 10px;"> suivants</i></a></li>
                {% else %}
                <li class="disabled"><a href="#!"><i class="material-icons" style="margin-left: 10px;"> suivants</i></a></li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </header>
</section>
{% endblock %}

purbeurre/main/templates/main/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Purbeurre</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">

                {% if user.is_authenticated %}
                <a class="nav-link" href="/logout/">Me déconnecter</a> {% else %}
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/login/">Me connecter</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/register/">Créer un compte</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

purbeurre/main/templates/main/homepage.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Pur Beurre</title>
  <link rel="icon" type="image/png" href="{% static 'img/logo_pur_beurre-favicon.png' %}" />
  <!-- Font Awesome Icons -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>

  <!-- Plugin CSS -->
  <link href="{% static 'vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

  <!-- Theme CSS - Includes Bootstrap -->
  <link href="{% static 'css/creative.min.css' %}" rel="stylesheet">

</head>

<body id="page-top" style="z-index: 0;">
  {% if messages %}
  {% for message in messages %}
<div class="container">
  <div class='row justify-content-center' >
    <div class="col-12">
      <div class="alert alert-success text-center " role="alert" style="z-index: 9999; position: absolute; margin-top: 50px;">
        {{message}}    
      </div>             
    </div>
  </div>
</div>
  {% endfor %}
  {% endif %}
  <!-- Navigation -->
            <nav class="navbar navbar-light navbar-expand-lg fixed-top " id="mainNav">
              <a class="navbar-brand js-scroll-trigger" href="/" style="width: 150px; height: 50px;">
              <img class="img-fluid " src="{% static 'img/logo_pur_beurre.png' %}" alt="" style="width: 30%;">
            Pur Beurre</a>
            <div class="navbar-toggler" data-toggle="collapse" data-target='#navbarResponsive'>
              <span class="navbar-toggler-icon"></span>
            </div>
       


          {% if user.is_authenticated %}
          <div class="collapse navbar-collapse mr-5 " id="navbarResponsive" >
            <ul class="navbar-nav ml-auto my-2 " >
            <li class="nav-item">
          <div class="input-group mb-3">

            {% block formu %}
            {% include './includes/searchbar.html' %}
            {% endblock %}
          </li>

          <li class="nav-item  mt-2">
            <a class="nav-link js-scroll-trigger" href="{% url 'main:account' %}"> Mon compte </a>
          </li>
          <li class="nav-item  mt-2">
            <a class="nav-link js-scroll-trigger" href="{% url 'main:saved' %}">Mes aliments</a>
          </li>
          <li class="nav-item  mt-2">
            <a class="nav-link js-scroll-trigger" href="{% url 'main:logout' %}">Déconnexion</a>
          </li>
          {% else %}
          <div class="collapse navbar-collapse mr-5" id="navbarResponsive">
            <ul class="navbar-nav ml-auto my-2 my-lg-0">
            <li class="nav-item">
                
              <a class="nav-link js-scroll-trigger" href="{% url 'main:login' %}">
              <i class="fa fa-user-circle" aria-hidden="true" id='login-button'></i> Me connecter
            </a>
            </li>            
          {% endif %}
        </ul>
      </div>
  </nav>

  <!-- Masthead -->

  {% block content %}

  <header class="masthead" style="z-index: 2;">
    <div class="container h-100">
      <div class="row h-100 align-items-center justify-content-center text-center">
        <div class="col-lg-10 align-self-end">
          <h1 class="text-uppercase text-white font-weight-bold" >Du gras oui, mais de qualité!</h1>
          <hr class="divider my-4">
        </div>
        <div class="col-lg-8 align-self-baseline">
          <h2 class="text-white-75 font-weight-light mb-5" id="subtitle">Trouvez un produit de substitution pour ceux que vous consommez tous les jours.</h2>
          <!-- <a class="btn btn-primary btn-xl js-scroll-trigger" href="#about">Chercher</a> -->
          {% block formular %}
          {% include './includes/searchbar.html' %}
          {% endblock %}
        </div>
      </div>
    </div>

  </header>
  {% endblock %}

  <!-- Services Section -->
  <section class="page-section" id="services">
    <div class="container">
    
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center">
            <h2 class="mt-0">Colette et Remy</h2>
            <hr class="divider my-4">
            <p class="text-muted mb-5">Pur Beurre est l'initiative de deux amoureux de la gastronomie française, Colette Tatou et Rémy, que vous avez déjà certainement rencontrés dans notre excellent restaurant Ratatouille. 
            </p>
          </div>
        </div>
        <div class="row" style="display: flex; align-items: center;justify-content: center;">
          <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
            <img class="img-fluid " src="{% static 'img/remy.jpg' %}" alt="">
            <div style="text-align: justify;">
            <p><strong>Remy</strong> : "Pour ma part je me rendais déjà dans bien des magasins car j'aime beaucoup me balader, surtout dans les caves et les cuisines. Je connaissais par coeur le contenu des boutiques bio (dont je raffole) ainsi que les ingrédients de tous les aliments vendus. Lorsque Colette m'a demandé si elle pouvait remplacer son Nutella matinal par un aliment plus sain, je savais tout de suite où le trouver. L'idée de Pur Beurre était née !"</p>
        </div>  
        </div>
          <div class="col-lg-4 mr-auto text-center">
            <img class="img-fluid " src="{% static 'img/colette-tatou-full.png' %}" alt="" ">
            <div style="text-align: justify;">
            <p><strong>Colette Tatou</strong>: "Nous aimons tous manger, surtout en France ! Personnellement, une baguette fraîche, du bon fromage de chèvre et un bon vin rouge me suffisent amplement. Comme tout le monde, je fais mes courses au supermarché. Mais petit à petit je me suis rendue compte, surtout lorsque nous avons ouvert le restaurant, que je pouvais remplacer les produits aseptisés que j'avais l'habitude d'acheter par de bons produits du terroir Et souvent pour le même prix !"</p>
            </div>
          </div>
        </div>
      </div>
  </section>

  <!-- Contact Section -->
  <section class="page-section" id="contact">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
          <h2 class="mt-0">Contactez-nous!</h2>
          <hr class="divider my-4">
          <p class="text-muted mb-5">Pour toute demande d'informations, n'hésitez pas prendre attache avec nous</p>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
          <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
          <div>+00 (00)0000000</div>
        </div>
        <div class="col-lg-4 mr-auto text-center">
          <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
          <!-- Make sure to change the email address in anchor text AND the link below! -->
          <a class="d-block" href="mailto:contact@purbeurre.com">mail@mail.com</a>
        </div>
      </div>
    </div>
  </section>

  <!-- Footer -->
  <footer class="bg-light py-5">
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <div class="small text-center text-muted"><a href='/mentions'>Mentions légales</a></div>
              </div>
              <div class="col-sm">
                
              </div>
              <div class="col-sm">
                <div class="small text-center text-muted">Contact</div>
              </div>

        </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'js/creative.min.js'%}"></script>

  <script>
    window.setTimeout(function() {
        $(".alert").fadeTo(500, 0).slideUp(500, function(){
            $(this).remove(); 
        });
    }, 3000);
  </script>
  
</body>

</html>

purbeurre/main/templates/main/login.html
{% extends 'main/homepage.html' %}

{% block content %}

{% load bootstrap4 %}
<header class="masthead">
    <div class="container h-100">
      <div class="row h-100 align-items-center justify-content-center text-center">
        {# Display a form #}
        <div class='row justify-content-center' >
          <div class="col-12">
             <div class="card">
               <div class="card-body">
                <form method="post" class="form" style="color: coral;">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary btn-block">Valider</button>
                {% endbuttons %}
                Si vous ne disposez déjà d'un compte, cliquez sur : <a href="/register"><strong>Créer un compte</strong></a>.
                </form>
              </div>
            </div>
          </div>
          </div>
      </div>
    </div>
  </header>
{% endblock %}